export type AdminLang = 'en' | 'fr';

const en = {
  navDashboard: 'Dashboard',
  navProducts: 'Products',
  navOrders: 'Orders',
  navAdmins: 'Admins',
  navSettings: 'Settings',
  logout: 'Logout',
  backToStorefront: 'Back to storefront',
  openMenu: 'Open menu',
  closeMenu: 'Close menu',
  loading: 'Loading admin...',
  cardProducts: 'Products',
  cardManaged: 'Managed in CMS',
  cardOrders: 'Orders',
  cardCod: 'COD orders',
  cardRevenue: 'Revenue',
  cardSales: 'Total sales',
  recentOrders: 'Recent Orders',
  noOrders: 'No orders yet.',
  thOrder: 'Order',
  thCustomer: 'Customer',
  thPhone: 'Phone',
  thTotal: 'Total',
  thStatus: 'Status',
  productsSub: 'Managed via CMS • changes appear on storefront',
  addProduct: 'Add product',
  formNew: 'Add new product',
  formEdit: 'Update product',
  thProduct: 'Product',
  thPrice: 'Price',
  thStock: 'Stock',
  thActions: 'Actions',
  outOfStock: 'Out of stock',
  edit: 'Edit',
  delete: 'Delete',
  confirm: 'Confirm',
  keep: 'Keep',
  productsEmpty: 'No products yet. Add the first one to populate the storefront.',
  ordersEmpty: 'No orders yet. Orders will appear here once customers check out.',
  fNameEn: 'Title (English)',
  fNameFr: 'Title (French)',
  fTagEn: 'Tag (English)',
  fTagFr: 'Tag (French)',
  fPrice: 'Price (DA)',
  fStock: 'Stock',
  fImage: 'Image URL or upload',
  fImagePh: 'Paste an image URL or upload below',
  fDragTitle: 'Drag and drop an image here',
  fDragOr: 'or',
  fChoose: 'Choose file',
  fFormats: 'PNG, JPG or WebP',
  fImageReady: 'Image ready',
  fRemove: 'Remove',
  fDescEn: 'Description (English)',
  fDescFr: 'Description (French)',
  fOos: 'Mark as out of stock',
  fCancel: 'Cancel',
  fAdd: 'Add product',
  fUpdate: 'Update product',
  fSaving: 'Saving…',
  eName: 'Title must be at least 3 characters.',
  eDesc: 'Description must be at least 10 characters.',
  ePrice: 'Price must be greater than 0.',
  eImage: 'An image URL or upload is required.',
  eStock: 'Stock must be a whole number of 0 or more.',
  eFile: 'Please choose an image file (PNG, JPG or WebP).',
  adminsTitle: 'Create admin user',
  adminsSub: 'Add a new admin with email and password.',
  adminsName: 'Full name',
  adminsCreate: 'Create admin',
  adminsList: 'Admin users',
  adminsCurrent: 'Current session',
  adminsEmpty: 'No admin users found.',
  settingsTitle: 'Settings',
  settingsSub: 'This section is managed via the existing CMS backend.',
  nProdUpdated: 'Product updated.',
  nProdAdded: 'Product added.',
  nProdDeleted: 'Product deleted.',
  nOrderUpdated: 'Order status updated.',
  nAdminCreated: 'Admin user created.',
  nAdminDeleted: 'Admin user deleted.',
  nErrSave: 'Could not save product.',
  nErrDelete: 'Could not delete product.',
  nErrOrder: 'Could not update order status.',
  nErrUserCreate: 'Could not create admin user.',
  nErrUserDelete: 'Could not delete admin user.',
  exportOrders: 'Export Excel',
  thCompany: 'Company',
  thDelivery: 'Delivery',
  homeDelivery: 'Home',
  stopDesk: 'Stop Desk',
  shipTitle: 'Shipping companies',
  shipSub: 'Choose the companies you work with. Active ones appear on orders.',
  shipAddPh: 'New company name',
  shipAdd: 'Add',
  shipActive: 'Active',
  shipPaused: 'Paused',
  shipEmpty: 'No shipping companies yet.',
  settingsShip: 'Shipping',
  nCompanyAdded: 'Company added.',
  nCompanyUpdated: 'Company updated.',
  nCompanyDeleted: 'Company deleted.',
  nErrCompany: 'Could not save company.',
  nErrCompanyDelete: 'Could not delete company.',
};

export type AdminStrings = typeof en;

const fr: AdminStrings = {
  navDashboard: 'Tableau de bord',
  navProducts: 'Produits',
  navOrders: 'Commandes',
  navAdmins: 'Admins',
  navSettings: 'Paramètres',
  logout: 'Déconnexion',
  backToStorefront: 'Retour à la boutique',
  openMenu: 'Ouvrir le menu',
  closeMenu: 'Fermer le menu',
  loading: 'Chargement…',
  cardProducts: 'Produits',
  cardManaged: 'Gérés via le CMS',
  cardOrders: 'Commandes',
  cardCod: 'Commandes COD',
  cardRevenue: 'Revenu',
  cardSales: 'Ventes totales',
  recentOrders: 'Commandes récentes',
  noOrders: 'Aucune commande pour le moment.',
  thOrder: 'Commande',
  thCustomer: 'Client',
  thPhone: 'Téléphone',
  thTotal: 'Total',
  thStatus: 'Statut',
  productsSub: 'Gérés via le CMS • visibles sur la boutique',
  addProduct: 'Ajouter un produit',
  formNew: 'Ajouter un produit',
  formEdit: 'Modifier le produit',
  thProduct: 'Produit',
  thPrice: 'Prix',
  thStock: 'Stock',
  thActions: 'Actions',
  outOfStock: 'Rupture de stock',
  edit: 'Modifier',
  delete: 'Supprimer',
  confirm: 'Confirmer',
  keep: 'Garder',
  productsEmpty: 'Aucun produit. Ajoutez le premier pour remplir la boutique.',
  ordersEmpty: 'Aucune commande. Elles apparaîtront après les achats clients.',
  fNameEn: 'Titre (anglais)',
  fNameFr: 'Titre (français)',
  fTagEn: 'Tag (anglais)',
  fTagFr: 'Tag (français)',
  fPrice: 'Prix (DA)',
  fStock: 'Stock',
  fImage: 'URL image ou téléversement',
  fImagePh: 'Collez une URL ou téléversez ci-dessous',
  fDragTitle: 'Glissez-déposez une image ici',
  fDragOr: 'ou',
  fChoose: 'Choisir un fichier',
  fFormats: 'PNG, JPG ou WebP',
  fImageReady: 'Image prête',
  fRemove: 'Retirer',
  fDescEn: 'Description (anglais)',
  fDescFr: 'Description (français)',
  fOos: 'Marquer en rupture de stock',
  fCancel: 'Annuler',
  fAdd: 'Ajouter le produit',
  fUpdate: 'Mettre à jour',
  fSaving: 'Enregistrement…',
  eName: 'Le titre doit contenir au moins 3 caractères.',
  eDesc: 'La description doit contenir au moins 10 caractères.',
  ePrice: 'Le prix doit être supérieur à 0.',
  eImage: 'Une URL image ou un téléversement est requis.',
  eStock: 'Le stock doit être un nombre entier de 0 ou plus.',
  eFile: 'Choisissez un fichier image (PNG, JPG ou WebP).',
  adminsTitle: 'Créer un admin',
  adminsSub: 'Ajoutez un admin avec email et mot de passe.',
  adminsName: 'Nom complet',
  adminsCreate: 'Créer l’admin',
  adminsList: 'Administrateurs',
  adminsCurrent: 'Session actuelle',
  adminsEmpty: 'Aucun administrateur trouvé.',
  settingsTitle: 'Paramètres',
  settingsSub: 'Cette section est gérée via le CMS existant.',
  nProdUpdated: 'Produit mis à jour.',
  nProdAdded: 'Produit ajouté.',
  nProdDeleted: 'Produit supprimé.',
  nOrderUpdated: 'Statut mis à jour.',
  nAdminCreated: 'Admin créé.',
  nAdminDeleted: 'Admin supprimé.',
  nErrSave: 'Enregistrement impossible.',
  nErrDelete: 'Suppression impossible.',
  nErrOrder: 'Mise à jour du statut impossible.',
  nErrUserCreate: 'Création de l’admin impossible.',
  nErrUserDelete: 'Suppression de l’admin impossible.',
  exportOrders: 'Exporter Excel',
  thCompany: 'Société',
  thDelivery: 'Livraison',
  homeDelivery: 'Domicile',
  stopDesk: 'Stop Desk',
  shipTitle: 'Sociétés de livraison',
  shipSub: 'Choisissez vos transporteurs. Les actifs apparaissent sur les commandes.',
  shipAddPh: 'Nom de la société',
  shipAdd: 'Ajouter',
  shipActive: 'Actif',
  shipPaused: 'En pause',
  shipEmpty: 'Aucune société.',
  settingsShip: 'Livraison',
  nCompanyAdded: 'Société ajoutée.',
  nCompanyUpdated: 'Société mise à jour.',
  nCompanyDeleted: 'Société supprimée.',
  nErrCompany: 'Enregistrement impossible.',
  nErrCompanyDelete: 'Suppression impossible.',
};

export const adminText: Record<AdminLang, AdminStrings> = { en, fr };
